### ISSUE TITLE
Breaking changes in v0.0.7

### ISSUE THREAD

**Issue by pcullin-ratio** [iron-io/ironcli#11]
The release of v0.0.7 seems to have caused some breaking changes to `upload` - most of which I've been able to overcome by inspecting the CLI code, but one of which I cannot seem to get past.

I first noticed the new version had been released when I saw `-name` was now required. After adding `-name` to my upload scripts, I also discovered the location of the flag was important (has to immediately follow `upload`).

Next, I discovered the `-zip` flag was explicitly required. Previously, I just had the path to the zip file in my script and it worked fine. Location was also significant with `-zip` - needs to follow the `-name` flag.

Finally, it appears `--stack` has not only been deprecated, but is not supported at all anymore. So I replaced `--stack node-0.10` with `iron/images:node-0.10`. The uploads actually do complete, but I get the error `400 Bad Request: Invalid stack. See http://dev.iron.io/worker/reference/environment/#default_language_versions for more information.`

In the HUD, I can see that my code was uploaded but it shows the stack as `default`. Furthermore, when I try to execute my code I get `Unhandled rejection Error: No code found to run for code.name = [MY_WORKER_NAME]`.

This is affecting our workflow pretty significantly, and I'd greatly appreciate some assistance!

**Comment by treeder** [comment]
We'll check this out shortly. The old way *should* still work.

**Comment by pcullin-ratio** [comment]
Thanks @treeder! By old way do you mean with `--stack`? I tried that too, and it resulted in issues with properly recognizing the `-zip` flag. Basically it looked like it skipped the stack argument and thought my command was part of the zip value.

**Comment by rdallman** [comment]
Hi @pcullin-ratio this is super weird, I tested for backward compatibility (aside from new name req.) with the following command: `iron --env prod worker upload --stack ruby-2.1 --name hello hello.zip ruby hello.rb ` and it totally works :( . sorry for the breakage, but thanks for the detailed feedback. will dig into this tomorrow. p.s. we're probably deprecating stack if you want to move the new "image" based way to stay ahead of the curve, but will shoot for backwards compat. we offer downloads of older versions in the meantime, but I will try to fix this up asap!

**Comment by pcullin-ratio** [comment]
Could it be because I didn't "double dash" my name arg? Is that required?

**Comment by rdallman** [comment]
nope, single vs double should be the same.

**Comment by rdallman** [comment]
the ordering thing is completely wackadoo

**Comment by pcullin-ratio** [comment]
Could the zip path issue I mentioned be caused by having a file path preceding my zip file name? More specifically something like this: `-zip ./workers/My_Worker.zip`. I wonder if the zip argument parsing logic in the CLI is only expecting `filename.zip` with no other preceding path info (and specifically not a `.`)?

**Comment by pcullin-ratio** [comment]
Here is a specific example of one of my upload commands, notice the zip path:
`iron --env test worker upload -name RSS_Parser_Worker -zip ./workers/rss/worker/RSS_Parser_Worker.zip iron/images:node-0.10 node worker.js`

**Comment by pcullin-ratio** [comment]
Following discussion with @treeder and @rdallman determined commands must be in the following format in 0.0.7:

`iron --env [ENVIRONMENT] worker upload -name [NAME] --stack [STACK] [FILENAME].zip [COMMAND]`

- Image name isn't currently supported as indicated (i.e. must include `--stack` and not use format like `iron/images:node-0.10` for example)
- `-zip` flag is not supported as documented - don't include it
- `-name` is now required and must immediately follow the `upload` command
