### ISSUE TITLE
Feature Request: Windows Compatibility

### ISSUE THREAD

**Issue by pcullin-ratio** [iron-io/ironcli#12]
When I attempt to install the CLI on a 64-bit Windows 8.1 machine via `curl -sSL http://get.iron.io/cli | sh`, I get the message `Error: you are not using a 64bit platform. Iron CLI currently only supports 64bit platforms.`

I'm guessing there is a larger Windows-incompatibility issue, since the error message is inaccurate in my case. Lack of Windows support for the CLI is a pretty significant issue for me and my team.

**Comment by rdallman** [comment]
@pyeremenko could you or somebody in kg test this please? need a way to automate windows builds for releases too if you guys have any ideas. thanks.

**Comment by pcullin-ratio** [comment]
Updated documentation has been added by @pyeremenko but it doesn't look like iron.exe for Windows is making it into your release process yet. It would be super duper appreciated if you could please include the compiled Windows iron.exe in each Github release for download from now on.

**Comment by pyeremenko** [comment]
@pcullin-ratio, please check https://github.com/iron-io/ironcli/releases/tag/v0.0.8 and try to use msi file there.

**Comment by rdallman** [comment]
this is part of release process now. if we can do any better, just let us know!
