### ISSUE TITLE
IronCLI breaking on Mac OS High Sierra

### ISSUE THREAD

**Issue by dylanz** [iron-io/ironcli#125]
"No Docker. I don’t have go installed. macOS High Sierra. I used the shell script to install ironcli: curl -sSL https://cli.iron.io/install | sh"

Stacktrace:  https://gist.github.com/dylanz/2b46b9d36cfdefeffa97c856e998aca2

**Comment by dylanz** [comment]
"I have an old Mac that can’t run docker. My workaround was to use brew: ‘brew install ironcli’. It installed the same version of ironcli and the command worked."

**Comment by jortizsao** [comment]
Same issue here

**Comment by rkononov** [comment]
@c0ze is this fixed? can i close it?

**Comment by c0ze** [comment]
@rkononov , yes I think so. We got feedback from some users as fixed.

**Comment by rkononov** [comment]
thanks!
