### ISSUE TITLE
400 Bad Request Error on upload with Iron Docker image

### ISSUE THREAD

**Issue by pcullin-ratio** [iron-io/ironcli#17]
According to the README, I'm using this command format to upload workers:
`iron worker upload --zip myworker.zip myworker iron/images:ruby-2.1 ruby hello.rb`

But I get the error:
`400 Bad Request: You do not have custom Docker images privilege. Contact support@iron.io to upgrade your account.`

I'm using the `iron/images:node-0.10` image, not my own custom image. So although the command supports this format, the service logic is not accepting it.

**Comment by rkononov** [comment]
public cluster updated, API servers rolled out, should be fixed

**Comment by rdallman** [comment]
@pcullin-ratio still having issues here?

**Comment by pcullin-ratio** [comment]
No, all good now.

**Comment by rdallman** [comment]
cool, thanks

**Comment by stephfz** [comment]
Hello,
I'm version  v0.0.15 and when executing
```
iron worker upload --name iron/images:ruby-2.1 --config-file config.json hello.zip ruby hello.rb
```
Getting the message  
```
400 Bad Request: You do not have custom Docker images privilege. Contact support@iron.io to upgrade your account.
```

I'm not using custom image, and still command is not being accepted

**Comment by rdallman** [comment]
@stephfz command should be `$ iron worker upload --name hello --zip hello.zip --config-file config.json iron/images:ruby-2.1 ruby hello.rb`
