### ISSUE TITLE
Mac build in release v0.0.14 not running

### ISSUE THREAD

**Issue by nimajalali** [iron-io/ironcli#25]
In release v0.0.14 the mac build looks to be an invalid binary.

Getting this
```
-bash: /usr/local/bin/iron: cannot execute binary file
```

For now I downloaded the last release v0.0.10 and everything is working fine.

**Comment by rdallman** [comment]
yep, looks like all the binaries are ELF. sorry about that, will re release right now

**Comment by rdallman** [comment]
here go, updated just now: https://github.com/iron-io/ironcli/releases/tag/v0.0.14

**Comment by rdallman** [comment]
let us know if this works so we can close it out, thank you!

**Comment by nimajalali** [comment]
Tested on mac and linux.

Looks Good :+1:
