### ISSUE TITLE
Use goptions?

### ISSUE THREAD

**Issue by treeder** [iron-io/ironcli#34]
What do you guys think of using goptions: https://github.com/voxelbrain/goptions

It's quite nice, much cleaner and easier than what we've got in here. Example:

https://github.com/treeder/docker-jockey/blob/master/dj.go#L27

@rdallman @rkononov

**Comment by rdallman** [comment]
looks like pretty much a drop in for `flag` package with some struct tags. like it, simple, don't need a whole framework. might look around the block for any others that are similar

**Comment by rkononov** [comment]
like it, pretty simple and cleaner

**Comment by ches** [comment]
It's heavier-weight perhaps, but FWIW I've found [Kingpin] quite pretty, in code and help output.

[Kingpin]: https://github.com/alecthomas/kingpin

**Comment by Nyarum** [comment]
Already exists with better solution.
