### ISSUE TITLE
Allow the setting up default_priority when uploading a worker code package

### ISSUE THREAD

**Issue by stengland** [iron-io/ironcli#38]
It would be very handy if you could set default_priority (as described in the api http://dev.iron.io/worker/reference/api/#upload_or_update_a_code_package) when uploading a worker. 
```
iron worker upload --zip myworker.zip --name myworker --default-priority 1 iron/images:ruby-2.1 ruby hello.rb
```

Currently the only way to do this seems to be by using curl as none of the iron client libraries seem to allow this.

**Comment by rdallman** [comment]
Hey @stengland , this is an easy one, will try to get this in today / tomorrow.

**Comment by stengland** [comment]
@rdallman That would be awesome thanks :smile:

**Comment by rdallman** [comment]
hey @stengland could you try https://github.com/iron-io/ironcli/releases/tag/v0.0.16 please ? thanks!

**Comment by stengland** [comment]
Yep that seems to be working. Thanks @rdallman
