### ISSUE TITLE
alpine binary release

### ISSUE THREAD

**Issue by elephantjim** [iron-io/ironcli#44]
Say, could you create a git release with a binary for alpine linux?  Alpine isn't compatible with the ironcli_linux binary because of the dependency on glibc (versus musl).  I know there's the iron/cli docker image.  However, if I want to include the iron binary in my own docker image -- but, say, not use "FROM iron/cli" as my base image -- I need to snarf the /usr/local/bin/iron binary from your image, and include it in my own.  That makes it much more difficult to get updates.  It would be much easier if you included alpine as a case in https://raw.githubusercontent.com/iron-io/ironcli/master/install.sh.  Say, test for /etc/lsb-release versus /etc/alpine-release.

**Comment by treeder** [comment]
Hi @elephantjim , good idea. You can build it yourself pretty easily, just clone this repo and run this shell script:

```sh
img=iron/go
wd=/go/src/github.com/iron-io/ironcli
docker run --rm -v "$PWD":$wd -w $wd $img go build -o iron
```

That's from this script that makes the iron/cli docker image: https://github.com/iron-io/ironcli/blob/master/build-docker.sh#L8

**Comment by elephantjim** [comment]
Ok, thanks!  We can add that as a workaround to our deployment pipeline for now.

**Comment by elephantjim** [comment]
@treeder Say, I've been having some problems with the Alpine build.  They happen with queues regardless of whether I build it myself or even if I `docker pull iron/cli`.  For example, if I try `iron mq list`, I get `400 Bad Request: Version mismatch: unsupported API version '3', expected version '2', please upgrade your client. See http://docs.iron.io`.  Is it hitting the wrong endpoint?

**Comment by rdallman** [comment]
Hi Jim, it means you are trying to use the cli against v2 -- we decided not to support mq v2 in the CLI since it is deprecated in favor of v3. happy to help get you moved over to v3, no plans to add v2 support to CLI (but patches accepted ;)

**Comment by elephantjim** [comment]
@rdallman Thanks.  I know that.

But you're not hearing me: this happens with the binary in iron/cli docker image.  It also happens if I try building the iron binary myself.  `iron mq list` fails with the above error.

**Comment by rdallman** [comment]
As far as I can understand, the CLI is behaving as expected  -- sorry if I am misunderstanding. If you'll pop into y'alls support channel we could go over your iron.json and maybe get more details. Are you saying there is an issue with the binary / docker or are you simply having issues getting an expected response (maybe this is what I'm confused about) ?

**Comment by elephantjim** [comment]
Try this:
```
docker pull iron/cli
docker run --rm iron/cli -project-id SOMEPROJECTID -token PROJECTTOKEN mq list
```

You'll get:
```
400 Bad Request: Version mismatch: unsupported API version '3', expected version '2', please upgrade your client. See http://docs.iron.io
```

**Comment by rdallman** [comment]
I see. so by default we're using a v2 URL when we should be using a v3 URL, correct ?

**Comment by elephantjim** [comment]
Yes, that seems to be the case.

**Comment by rdallman** [comment]
thanks, filed a bug. workaround is change host to `mq-aws-us-east-1-1.iron.io` until we get a patch in

**Comment by elephantjim** [comment]
Ah, ok.  Cool beans.  Thanks!

**Comment by rdallman** [comment]
https://github.com/iron-io/iron_mq_ruby/commit/7e912aceffd8381f82eeed18d25dff96dc816653

**Comment by treeder** [comment]
Can we close this?

**Comment by elephantjim** [comment]
It's up to you.

The original issue was that there is no git release with a binary for alpine linux.  That's still true.  All the iron.io docker images use alpine, but there's no release in this repo that's binary compatible with alpine (because of libc).

My testing around that issue eventually turned up another issue, the default version/host for queues.  That issue was resolved.

**Comment by tunezaq** [comment]
@treeder 
How about replacing the ironcli_linux binary with a statically linked version?
```
CGO_ENABLED=0 GOOS=linux go build -o ironcli_linux .
```

Tested this on a CentOS box and in a docker alpine container and it worked fine.

**Comment by rdallman** [comment]
done. thanks @tunezaq
