### ISSUE TITLE
A way to assign a label via the CLI?

### ISSUE THREAD

**Issue by kevmoo** [iron-io/ironcli#45]
It'd be really nice...

**Comment by rdallman** [comment]
sure, easy to add. will add a ticket

**Comment by rdallman** [comment]
done. thanks @kevmoo

**Comment by kevmoo** [comment]
Thank you, @rdallman !

Will this be part of 0.0.17?

**Comment by rdallman** [comment]
done https://github.com/iron-io/ironcli/releases/tag/v0.0.17

**Comment by kevmoo** [comment]
One line to change? https://github.com/iron-io/ironcli/blob/master/install.sh#L12

**Comment by rdallman** [comment]
should be fixed -- push failed.
