### ISSUE TITLE
Windows ironcli.exe returning version mismatch (unsupported API version) error on upload

### ISSUE THREAD

**Issue by lauraweindorf** [iron-io/ironcli#57]
With iron.json containing just project_id and token, ironcli.exe upload returns version mismatch error:

`400 Bad Request: Version mismatch: unsupported API version '2', expected version '3', please upgrade your client. See http//docs.iron.io`

I'm using the latest ironcli.exe version (0.0.20).

When I explicitly added the host entry to my iron.json, it worked. I was thinking this is an issue and that it should be using the host below as a default?

`"host": "worker-aws-us-east-1.iron.io"`

**Comment by lauraweindorf** [comment]
Sorry! This issue can be closed. 

I forgot that I previously set the environment variable `IRON_HOST` in my profile to the new MQv3 host to get my queue stuff working. That value was overriding what I had in my local `iron.json` for my worker :-P.

**Comment by rdallman** [comment]
Thanks, we have improved that error message in the next release.
