### ISSUE TITLE
CLI not accepting config file flag

### ISSUE THREAD

**Issue by andrest** [iron-io/ironcli#61]
```
$ iron worker upload --config-file $PWD/scripts/iron.json --zip build/sms-customer.js.zip --name biller iron/node node index.js
did not find project id in any config files or env variables
```

```
$ cat $PWD/scripts/iron.json
{"token":"xxxxxxxxxxxxx","project_id":"xxxxxxxxxxxxx"}
```

What's going on here?

**Comment by rdallman** [comment]
Hi @andrest, `--config-file` is for uploading a config file into the worker, not the config file that we use to authenticate your request to us. If you place `$PWD/scripts/iron.json` in `$PWD/iron.json` then that should work, another alternative is using env vars, e.g. `IRON_TOKEN=xxx`. Does this answer your question?

**Comment by andrest** [comment]
I'd like to keep the .iron file in config/scripts folder, is there any way to specify the file location with the CLI tool?

**Comment by rdallman** [comment]
There is not right now, I guess we could have an env var that points to a config file? we're trying to get everybody moved over to env vars now. pull requests welcome if it's urgent on your end.

**Comment by andrest** [comment]
I solved it by calling iron CLI from my build script in /scripts. This lets me do npm run build anywhere, no matter my current directory. I guess environment variables would work too. I'll close this. Thanks for the reply! :)

**Comment by andrest** [comment]
@rdallman it seems the docs may be a bit out of sync in regards to the preferred approach http://dev.iron.io/worker/languages/nodejs/ still
