### ISSUE TITLE
Upload not respecting iron.json in zip package

### ISSUE THREAD

**Issue by pcullin-ratio** [iron-io/ironcli#7]
In attempting to upload a worker that included an iron.json file, I encountered the error:
"did not find project id in any config files or env variables"

The same iron.json file works fine with the Ruby CLI. Do I need to specify my iron.json file differently with the new CLI, or is it simply not set up to handle iron.json configuration files yet?

**Comment by rdallman** [comment]
Hi Paul, we've observed this with certain cross compiled builds but we do support iron.json likely right where you have it. what platform are you trying on? we could probably get a new build up for it soon to see that this gets fixed.

**Comment by pcullin-ratio** [comment]
Thanks for the quick reply! This is for a NodeJS worker.

I also noticed that the name of the worker once it was uploaded corresponded to the name of the zip package provided to the upload. Is there another way to specify the name of the worker similar to how you could using the old .worker files?

**Comment by rdallman** [comment]
> This is for a NodeJS worker.

oops, sorry, uploading from linux/windows/mac ?

> I also noticed that the name of the worker once it was uploaded corresponded to the name of the zip package provided to the upload. Is there another way to specify the name of the worker similar to how you could using the old .worker files?

easy fix, just added https://github.com/iron-io/ironcli/commit/8e7ff732b1278cf907eecd4db96b8b96a87cd49f . let me know what platform you're on and might could get you a build quickly. `$ iron worker upload -name yournamehere`

**Comment by pcullin-ratio** [comment]
This is being run from the Shippable CI service, which in this case uses Ubuntu (via their own Docker image).


Sent by Outlook<http://taps.io/outlookmobile> for Android



On Wed, Apr 8, 2015 at 7:07 PM -0700, "Reed Allman" <notifications@github.com<mailto:notifications@github.com>> wrote:


This is for a NodeJS worker.

oops, sorry, uploading from linux/windows/mac ?

I also noticed that the name of the worker once it was uploaded corresponded to the name of the zip package provided to the upload. Is there another way to specify the name of the worker similar to how you could using the old .worker files?

easy fix, just added 8e7ff73<https://github.com/iron-io/ironcli/commit/8e7ff732b1278cf907eecd4db96b8b96a87cd49f> . let me know what platform you're on and might could get you a build quickly. $ iron worker upload -name yournamehere

-

**Comment by rdallman** [comment]
perfect, thanks. should be able to get you a build really quick then. I just tried out `0.0.6` on a fresh linux box though and it seems to find my `~/.iron.json` fine. could you confirm you're using `0.0.6` (from `get.iron.io/cli` ?) -- or if not, which build are you using?

**Comment by rdallman** [comment]
fwiw mine looks like (ruby and go do have different parsers, thinking maybe a bug, they should both evaluate the same):

```
{
  "iron_worker":{
    "project_id":"my_project_id_here",
    "token":"my_token_here"
  }
}
```

**Comment by pcullin-ratio** [comment]
Mine is segregated by environment name like this:

{
  "test": {
    "token": "test_token",
    "project_id": "test_project_id"
  },
  "stage": {
    "token": "staging_token",
    "project_id": "staging_project_id"
  },
  "production": {
    "token": "production_token",
    "project_id": "production_project_id"
  }
}

As I mentioned, this same iron.json file has been used in the past with the old CLI. Specifying a service (i.e. iron_worker) in the json has always been optional in the past, and used for overriding global configuration settings. Can you verify if this has changed?

Also, I noticed my file is called iron.json, not .iron.json. Is that a problem?

**Comment by pcullin-ratio** [comment]
This is what I'm referring to (from the Iron CLI v1.0 Workflow article):

Upload with Multiple Environments

It is common to want to use IronWorker across many different development environments.

When uploading your worker you can specify an environment via the ** --env ** (or ** -e ** option).

Command Line
$ iron_worker upload helloworker --env development
$ iron_worker upload helloworker --env staging
$ iron_worker upload helloworker -e test
$ iron_worker upload helloworker -e production
We reccomend you create seperate projects for each development environment. Below is an example of a typical iron.json with multiple environments iron.json into multiple development environments via different project id's and tokens.

{
  "production": {
    "token": "AAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "project_id": "000000000000000000000001"
  },
  "staging": {
    "token": "BBBBBBBBBBBBBBBBBBBBBBBBBB",
    "project_id": "000000000000000000000002"
  },
  "development": {
    "token": "CCCCCCCCCCCCCCCCCCCCCCCCCC",
    "project_id": "000000000000000000000003"
  },
  "test": {
    "token": "DDDDDDDDDDDDDDDDDDDDDDDDDD",
    "project_id": "000000000000000000000004"
  }
}

**Comment by treeder** [comment]
@pcullin-ratio we're going to dig into this, but as a temporary workaround if you need to get it working now, you can just modify the iron.json file and just use the basic:

```
{ "project_id": "123", "token": "abc" }
```

And change it for each upload you are trying to do.

**Comment by pcullin-ratio** [comment]
Unfortunately that won't work for my current scenario, but I can go back to using the Ruby version for now as a workaround and keep tabs on progress in getting this implemented. Thanks for looking into it!

**Comment by rdallman** [comment]
@pcullin-ratio thanks for details! we do support the different environments like you ask, but the flag has moved. we will document this better for future users, thanks for the feedback.

```
$ iron -env test worker upload -stack ruby-2.1 test.zip ruby -v
```

I've tested this and it seems to work for me, could you verify it works on your end?

**Comment by pcullin-ratio** [comment]
No, this is not working for me. I included my iron.json file in the zip package being uploaded via the CLI, but still get the error "did not find project id in any config files or env variables".

**Comment by pcullin-ratio** [comment]
Also, having the -env flag in the middle of the command like that is problematic from an npm scripting perspective (you can only pass arguments to the end of commands using npm, which I am for CI scripting).

But back to the problem at hand - do you think you'll be able to fix this issue soon? I'm happy to engage in a pairing session or something if that is more efficient.

**Comment by treeder** [comment]
Hi @pcullin-ratio , could you post the exact command you are running the output/error?

**Comment by pcullin-ratio** [comment]
I'm running into two main issues currently:
1) Still not able to get the CLI to recognize a specific environment using the iron.json I'm including within the uploaded package (more details already covered in this issue from previously)
2) Upon successful upload of a zip package using the CLI, when I queue the worker it runs but errors and logs output to the console indicating my worker script file does not exist: `sh: 1: loadbalancer.js: not found`.

The package I'm uploading via the CLI includes:
- loadbalancer.js - my NodeJS worker script
- node_modules - dependencies folder with all dependencies included
- iron.json - multi-environment Iron service config file (tokens and project id's for multiple environments)
- sample.payload.json - sample payload file for reference
.npmrc - a custom npm configuration...but not ultimately used in the worker (it's there for CI config)

This is the script I'm running to upload the worker (assumes the zip package exists and is named "Content_NLP_LB.zip":
`iron worker upload --stack node-0.10 Content_NLP_LB.zip loadbalancer.js`

I have removed the reference to environment in the command, as I've not been able to get that to work successfully and am just using environment variables.

**Comment by treeder** [comment]
Regarding the upload command, looks like your'e missing the node command. You have:

```
iron worker upload --stack node-0.10 Content_NLP_LB.zip loadbalancer.js
```

It should be:

```
iron worker upload --stack node-0.10 Content_NLP_LB.zip node loadbalancer.js
```

**Comment by rdallman** [comment]
resolved via slack, updating docs meow
