### ISSUE TITLE
Invalid image name format

### ISSUE THREAD

**Issue by pulkitsinghal** [iron-io/ironcli#71]
When running:
`iron worker upload node:0.10.44 node hello.js`

I receive an error stating:
`400 Bad Request: Invalid image name format`

`node:0.10.44` is a valid image name format just like `iron/node`
Can you comment if you agree this should be fixed or not?

**Comment by nikhilm** [comment]
Thanks for bringing this to our attention. It is indeed a bug. I will update this once we have a fix.

**Comment by noqcks** [comment]
fixed in https://github.com/iron-io/go/pull/682

closing.
