### ISSUE TITLE
Docker version local works but not remote

### ISSUE THREAD

**Issue by alnutile** [iron-io/ironcli#8]
Goal was to working locally with docker images per the beta docs and then once uploaded that same worker would work.

Ran locally
docker run --rm -v "$(pwd)":/worker -w /worker iron/images:php-5.6 sh -c "php /worker/workers/PDF2PagesWorker.php -payload tests/testspayload.json"

(tried 5.5 and 5.4 as well locally I think one did not work eg convert not found)

Then when I uploaded this

iron worker upload --stack php-5.6 PDF2PagesWorker.zip php workers/PDF2PagesWorker.php

again tried 5.4 5.5. 5.6 it failed as seen here

https://hud.iron.io/tq/projects/54dceb433373aa0006000121/tasks/5536b0912df6ff6add01b30f/log

But looking here the worker is at 5.5 
https://hud.iron.io/tq/projects/54dceb433373aa0006000121/code/5536481c93506b0d73001114

But per your stack notes on http://dev.iron.io/worker/beta/getting_started/
which leads to http://dev.iron.io/worker/reference/environment/#default_language_versions

https://gist.github.com/freeman1988/6865edb4410e934a3ca6
~~~
imagemagick	8:6.6.9.7-5ubuntu3.3
imagemagick-common	8:6.6.9.7-5ubuntu3.3
~~~

which has convert 

I ran 

~~~
docker run -it -v "$(pwd)":/worker -w /worker iron/images:php-5.6 /bin/bash
~~~

and it has it

I ran 

~~~
docker run -it -v "$(pwd)":/worker -w /worker iron/images:php-5.5 /bin/bash
~~~

and it does not.

I then ran

~~~
docker run -it -v "$(pwd)":/worker -w /worker iron/images:php-5.4 /bin/bash
~~~

And it does have it

but then I ran 

~~~
iron worker upload --stack php-5.4 PDF2PagesWorker.zip php workers/PDF2PagesWorker.php
----->  Configuring client
        Project 'DiffTool' with id='54dceb433373aa0006000121'
----->  Uploading worker 'PDF2PagesWorker'
        Uploaded code package with id='5536481c93506b0d73001114'
        Check 'https://hud.iron.io/tq/projects/54dceb433373aa0006000121/code/5536481c93506b0d73001114' for more info
~~~

But then again the rev might not change cause the zip has not changed.

Sorry tired and need to call it quits but wanted to get this in before the day was done.

Version
iron cli 0.0.6

Thanks looking forward to working more on docker speeds up the work a ton

**Comment by alnutile** [comment]
one more addition

did this

~~~
iron worker upload --stack php-5.4 PDF2PagesWorker.zip php workers/PDF2PagesWorker.php
~~~

then

~~~
iron worker queue --wait -payload-file testspayload.json PDF2PagesWorker
~~~

and still 5.5 and a fail of course since it is missing convert

https://hud.iron.io/tq/projects/54dceb433373aa0006000121/tasks/553701562ca9500414004d0f

**Comment by treeder** [comment]
@alnutile you definitely need to change the zip for a new upload to take hold, can you add a character to one of your files, rezip it, then reupload with 5.6?

**Comment by alnutile** [comment]
thanks trying now

**Comment by alnutile** [comment]
that worked to increase the version as seen here
https://hud.iron.io/tq/projects/54dceb433373aa0006000121/tasks/5537eb2cd24e3911a601b81a

I can make a new ticket for the next one if needed. I see this locally too when I run 

~~~
docker run --rm -v "$(pwd)":/worker -w /worker iron/images:php-5.6 sh -c "php /worker/workers/PDF2PagesWorker.php -payload tests/testspayload.json"
~~~

error as seen in the logs of the link above

~~~
 [ErrorException]                                     
  syntax error, unexpected '{' in iron.json on line 1  
~~~

Locally if I remote iron.json or empty it out all is well.

Here is what is has

~~~
{ "token": "foo", "project_id": "bar" }
~~~

no funny spaces or characters etc.

Should I close this ticket and make a new one for that? Thanks again

**Comment by treeder** [comment]
You get that error locally, but not remote?

**Comment by alnutile** [comment]
that was on remote and local.

So if I leave the iron.json file there on my local and run 

~~~
docker run --rm -v "$(pwd)":/worker -w /worker iron/images:php-5.6 sh -c "php /worker/workers/PDF2PagesWorker.php -payload tests/testspayload.json"
~~~

I get the error AND if I upload that to iron I get the error. My local does not need it so I can remove it while I test locally and all is fine.

**Comment by alnutile** [comment]
So I removed the iron.json file added .iron.json to my home folder and uploaded using this command 

~~~
IRON_PROJECT_ID=foo iron worker upload --stack php-5.6 PDF2PagesWorker.zip php workers/PDF2PagesWorker.php
~~~

To get around that issue

## Next Issue

overall I do not think I am running the same versions cause locally this works great but when I upload it I get the error seen here

https://hud.iron.io/tq/projects/54dceb433373aa0006000121/tasks/5538c2232df6ff606900cd5f/log

>Error with the process Error running pdf to images job convert.im6: `%s' (%d) "gs" -q -dQUIET -dSAFER -dBATCH -dNOPAUSE -dNOPROMPT -dMaxBitmap=500000000 -dAlignToPixels=0 -dGridFitTT=2 "-sDEVICE=pngalpha" -dTextAlphaBits=4 -dGraphicsAlphaBits=4 "-r600x600"  "-sOutputFile=/tmp/magick-u0ucxvMg--0000001" "-f/tmp/magick-VOfL2Kes" "-f/tmp/magick-l1BRinHD" @ error/utility.c/SystemCommand/1890.
convert.im6: Postscript delegate failed `/mnt/task/storage/bundles/mock-project-1/requests/mock-request-5/diffs/pdfa_to_pages/page_002.pdf': No such file or directory @ error/pdf.c/ReadPDFImage/677.
convert.im6: no images defined `/mnt/task/storage/bundles/mock-project-1/requests/mock-request-5/diffs/pdfa_to_images/page_002.png' @ error/convert.c/ConvertImageCommand/3044.
 project id mock-project-1 request id mock-request-5 set a message: 
 Error running pdf to images job convert.im6: `%s' (%d) "gs" -q -dQUIET -dSAFER -dBATCH -dNOPAUSE -dNOPROMPT -dMaxBitmap=500000000 -dAlignToPixels=0 -dGridFitTT=2 "-sDEVICE=pngalpha" -dTextAlphaBits=4 -dGraphicsAlphaBits=4 "-r600x600"  "-sOutputFile=/tmp/magick-u0ucxvMg--0000001" "-f/tmp/magick-VOfL2Kes" "-f/tmp/magick-l1BRinHD" @ error/utility.c/SystemCommand/1890.
convert.im6: Postscript delegate failed `/mnt/task/storage/bundles/mock-project-1/requests/mock-request-5/diffs/pdfa_to_pages/page_002.pdf': No such file or directory @ error/pdf.c/ReadPDFImage/677.
convert.im6: no images defined `/mnt/task/storage/bundles/mock-project-1/requests/mock-request-5/diffs/pdfa_to_images/page_002.png' @ error/convert.c/ConvertImageCommand/3044.

Looking at the `/mnt/task` shows this is not docker since docker would be `/worker`?

Also, locally, I can run this again and again and it works just fine as I note in the `docker run` commands above.

**Comment by alnutile** [comment]
btw it is clear now that the files are not there. So either my always working download failed?
Again just trying to see why it works here 100% of the time and not there.

Thanks again!

**Comment by alnutile** [comment]
I tested a bit more to make sure the files are there and they are.
So at this point not sure what direction to go. Considering it works locally using docker run then I assume right now what I am running on iron is not docker?

**Comment by rkononov** [comment]
@alnutile iron is using docker for sure, there are few differences
1) we're launching all user's code under user nobody
2) home dir is at /mnt/task

**Comment by alnutile** [comment]
thanks @rkononov since none of my paths are the issue then why does it work when I run 

~~~
docker run --rm -v "$(pwd)":/worker -w /worker iron/images:php-5.6 sh -c "php /worker/workers/PDF2PagesWorker.php -payload tests/testspayload.json"
~~~

on my machine but dies there due to file folder issues?

My code is based on relative paths btw.

**Comment by alnutile** [comment]
trying now btw with a new chmod

~~~
    private function makeSureFoldersAreReadWrite()
    {
        $storage = storage_path();

        exec("chmod -R 777 {$storage}", $output);

        if(!File::isWritable(storage_path()))
            throw new \Exception(sprintf("Folder not writable %s message %s", storage_path(), implode("\n", $output)));
    }
~~~

**Comment by alnutile** [comment]
nope.

One other thought is `convert` uses a temp folder `-sOutputFile=/tmp/` during the process. Is this not writable?

**Comment by rkononov** [comment]
try to use /mnt/task/tmp instead of /tmp

**Comment by alnutile** [comment]
thanks trying now

**Comment by alnutile** [comment]
still no luck. Tried /mnt/task/tmp and storage that I am using for initial images.

I can keep working on this with you or I can use gem install iron_worker_ng and use ver 1 to switch this back?

**Comment by rkononov** [comment]
if you share to me PDF2PagesWorker.php or simplified version of it (like just using convert that is working locally but doens't work on backend) i could try to debug directly on server side

**Comment by alnutile** [comment]
the worker file calls in other classes so I will share below the process and files you need


Convert run like this

~~~
convert -density 600 /some/pdf/file/foo.pdf /some/image/output/foo.pdf
~~~

We do this over a directory but I assume you will see it with one file.

I tried your temp idea as such

~~~
export MAGICK_TMPDIR=/mnt/task/tmp && convert -density 600 /some/pdf/file/foo.pdf /some/image/output/foo.pdf
~~~

But that did not seem to help

Finally the pdf file you can use to make sure that is not an issue on your end

https://www.dropbox.com/s/c5mjwnpr6d78ak2/page_001.pdf?dl=0

**Comment by alnutile** [comment]
any luck on this? I tried iron_worker and can focus on rolling back to that if needed?

But then I have to shift some code around since there laravel examples you have are for Laravel 4 and do not work with Laravel 5 due to previous issues in namespacing and curl I reported,

**Comment by treeder** [comment]
@alnutile can you email me at travis at iron dot io so we can get on a real-time chat?

**Comment by alnutile** [comment]
for sure

**Comment by alnutile** [comment]
sent email taking lunch for the next hour, going to talk to Tom soon too about going up to a custom/production level worker plan btw since we are going to be doing a lot of this when the app is released

**Comment by treeder** [comment]
@alnutile can we close this now?
