### ISSUE TITLE
Cover "Stacks" endpoint

### ISSUE THREAD

**Issue by Nyarum** [iron-io/ironcli#85]
From http://dev.iron.io/worker/reference/api/ and https://github.com/iron-io/ironcli/issues/80

What we need?
- [ ] Cover this endpoints in separate package.
- [ ] Cover commands for that in CLI

**Comment by treeder** [comment]
We don't need this one covered anymore, stacks are deprecated.

**Comment by Nyarum** [comment]
Closed
