### ISSUE TITLE
Setup circle ci and tests for existing things to ensure we don't break anything with new changes

### ISSUE THREAD

**Issue by treeder** [iron-io/ironcli#86]
Should be done before  #79 and #80.

**Comment by treeder** [comment]
cc @pedronassar @Nyarum

**Comment by Nyarum** [comment]
@treeder for now we don't have any tests.
Are we need to write their or use just "go build" for test?

**Comment by treeder** [comment]
we should write some tests

**Comment by Nyarum** [comment]
@treeder maybe we can do it after #79?
Because there is a many changes and we can test some commands manually, for next we'll start to write tests for commands.

**Comment by Nyarum** [comment]
Now #79 has merged so I started a deep investigate for better testing our cli.

**Comment by Nyarum** [comment]
Done unit tests with a minimal cover.
