### ISSUE TITLE
Create new release - current release is 0.1.2 which is old

### ISSUE THREAD

**Issue by treeder** [iron-io/ironcli#91]
Preferably we should just do a release off master and automate it. But for now, just do our regular release process which I **think** is just pushing to the `release` branch, then circle will do the release.

**Comment by rdallman** [comment]
push to prod branch... i'm skeptical that everything broke from that giant
patch so we should all probably try it for a while

**Comment by nikhilm** [comment]
Blockers #100 #99 #98 #97 #96 #95 at the very least.

**Comment by Nyarum** [comment]
@treeder now we have the 0.1.3 version - https://github.com/iron-io/ironcli/releases/tag/0.1.3
